"""new columns for Game

Revision ID: 2088fc910e4b
Revises: e1acc0872c9e
Create Date: 2023-06-05 15:49:12.851804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2088fc910e4b'
down_revision = 'e1acc0872c9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('pairs', sa.String(), nullable=True))
    op.add_column('games', sa.Column('solution_dict', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'solution_dict')
    op.drop_column('games', 'pairs')
    # ### end Alembic commands ###
