"""added columns to game

Revision ID: 90f5dbea3dd1
Revises: abd52297a937
Create Date: 2023-06-05 09:56:47.259841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f5dbea3dd1'
down_revision = 'abd52297a937'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('groupings', sa.String(), nullable=True))
    op.add_column('games', sa.Column('board', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'board')
    op.drop_column('games', 'groupings')
    # ### end Alembic commands ###
