"""added special column for user

Revision ID: e1acc0872c9e
Revises: 90f5dbea3dd1
Create Date: 2023-06-05 10:35:01.861726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1acc0872c9e'
down_revision = '90f5dbea3dd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('special', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'special')
    # ### end Alembic commands ###
